# Generated by Django 2.0.6 on 2018-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='placar1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jogo',
            name='placar2',
            field=models.IntegerField(default=0),
        ),
    ]
